print("¡Hola, mundo!")
print("Bonjour le monde!")
print("Hello, world!")
print("Hallo, Welt!")
print("Ciao, mondo!")
print("こんにちは、世界！")
print("안녕하세요, 세계!")
print("Привет, мир!")
print("مرحبا بالعالم!")
print("שלום עולם!")
print("नमस्ते दुनिया!")
print("Olá, mundo!")
print("Hej världen!")